# This file is used to run a development environment for the smart mirror dashboard using Docker Compose.
# It defines three services: MongoDB, the API server, and the AI service.
# Each service is connected to a common network for communication.

services:
  smart-mirror-mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - smart-mirror-net

  smart-mirror-api:
    image: mohamedfouad71/smart-mirror-api:e2f8e21599d5802f25dedf855727bfa91a70d87c
    ports:
      - '3000:3000'
    env_file:
      - .env-api
    depends_on:
      - smart-mirror-mongo
    networks:
      - smart-mirror-net

  smart-mirror-ai:
    image: mohamedfouad71/smart-mirror-ai:d6d1a6677945b781f78305941afffb414c07ba11
    env_file:
      - .env-ai
    depends_on:
      - smart-mirror-api
    networks:
      - smart-mirror-net

networks:
  smart-mirror-net:
    driver: bridge
