on:
  push: 
      branches: ["devops","main"]
  pull_request:
      branches: ["devops","main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      
      # using sha for security purposes
      - name: Proof HTML
        uses: anishathalye/proof-html@a76b66427e600c6992e8937a741afffd2264a613
        with:
          directory: .

  build:
    needs: proof
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  deploy_on_github_pages:
    needs: proof
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Cleanup unwanted files
        run: |
          sed -i 's/\r$//' .pagesignore
          cat .pagesignore | xargs -I {} sh -c 'rm -rf {}'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Inject Production Configurations
        run: |
          find . -type f \( -name "*.js" -o -name "*.html" \) -exec sed -i "s|http://localhost:3000|${{ secrets.BACKEND_URL }}|g" {} +
     
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4